#include <stdio.h>
#include <string.h>
#include <stdlib.h>

const char *entrada = "NOWFAIRHIPPOLYTAOURNUPTIALHOURDRAWSONAPACEFOURHAPPYDAYSBRINGINANOTHERMOONBUTOMETHINKSHOWSLOWTHISOLDMOONWANESSHELINGERSMYDESIRESLIKETOASTEPDAMEORADOWAGERLONGWITHERINGOUTAYOUNGMANREVENUEHIPPOLYTAFOURDAYSWILLQUICKLYSTEEPTHEMSELVESINNIGHTFOURNIGHTSWILLQUICKLYDREAMAWAYTHETIMEANDTHENTHEMOONLIKETOASILVERBOWNEWBENTINHEAVENSHALLBEHOLDTHENIGHTOFOURSOLEMNITIESTHESEUSGOPHILOSTRATESTIRUPTHEATHENIANYOUTHTOMERRIMENTSAWAKETHEPERTANDNIMBLESPIRITOFMIRTHTURNMELANCHOLYFORTHTOFUNERALSTHEPALECOMPANIONISNOTFOROURPOMPEXITPHILOSTRATEHIPPOLYTAIWOODTHEEWITHMYSWORDANDWONTHYLOVEDOINGTHEEINJURIESBUTIWILLWEDTHEEINANOTHERKEYWITHPOMPWITHTRIUMPHANDWITHREVELLINGENTEREGEUSHERMIALYSANDERANDDEMETRIUSEGEUSHAPPYBETHESEUSOURRENOWNEDDUKETHESEUSTHANKSGOODEGEUSWHATSTHENEWSWITHTHEEEGEUSFULLOFVEXATIONCOMEIWITHCOMPLAINTAGAINSTMYCHILDMYDAUGHTERHERMIASTANDFORTHDEMETRIUSMYNOBLELORDTHISMANHATHMYCONSENTTOMARRYHERSTANDFORTHLYSANDERANDMYGRACIOUSDUKETHISMANHATHBEWITCHDTHEBOSOMOFMYCHILDTHOUTHOULYSANDERTHOUHASTGIVENHERRHYMESANDINTERCHANGEDLOVETOKENSWITHMYCHILDTHOUHASTBYMOONLIGHTATHERWINDOWSUNGWITHFEIGNINGVOICEVERSESOFFEIGNINGLOVEANDSTOLENTHEIMPRESSIONOFHERFANTASYWITHBRACELETSOFTHYHAIRRINGSGAWDSCONCEITSKNACKSTRIFLESNOSEGAYSSWEETMEATSMESSENGERSOFSTRONGPREVAILMENTINUNHARDENDYOUTHWITHCUNNINGHASTTHOUFILCHDMYDAUGHTERSHEARTTURNDHEROBEDIENCEWHICHISDUETOMETOSTUBBORNHARSHNESSANDMYGRACIOUSDUKEBEITSOSHEWILLNOTHEREBEFOREYOURGRACECONSENTTOMARRYWITHDEMETRIUSIBEGTHEANCIENTPRIVILEGEOFATHENSASSHEISMINEIMAYDISPOSEOFHERWHICHSHALLBEEITHERTOTHISGENTLEMANORTOHERDEATHACCORDINGTOOURLAWIMMEDIATELYPROVIDEDINTHATCASETHESEUSWHATSAYYOUHERMIABEADVISEDFAIRMAIDTOYOUYOURFATHERSHOULDBEASAGODONETHATCOMPOSEDYOURBEAUTIESYEAANDONETOWHOMYOUAREBUTASAFORMINWAXBYHIMIMPRINTEDANDWITHINHISPOWERTOLEAVETHEFIGUREORDISFIGUREITDEMETRIUSISAWORTHYGENTLEMANHERMIASOISLYSANDERTHESEUSINHIMSELFHEISBUTINTHISKINDWANTINGYOURFATHERSVOICETHEOTHERMUSTBEHELDTHEWORTHIERHERMIAIWOULDMYFATHERLOOKDBUTWITHMYEYESTHESEUSRATHERYOUREYESMUSTWITHHISJUDGMENTLOOKHERMIAIDOENTREATYOURGRACETOPARDONMEIKNOWNOTBYWHATPOWERIAMMADEBOLDNORHOWITMAYCONCERNMYMODESTYINSUCHAPRESENCEHERETOPLEADMYTHOUGHTSBUTIBESEECHYOURGRACETHATIMAYKNOWTHEWORSTTHATMAYBEFALLMEINTHISCASEIFIREFUSETOWEDDEMETRIUSTHESEUSEITHERTODIETHEDEATHORTOABJUREFOREVERTHESOCIETYOFMENTHEREFOREFAIRHERMIAQUESTIONYOURDESIRESKNOWOFYOURYOUTHEXAMINEWELLYOURBLOODWHETHERIFYOUYIELDNOTTOYOURFATHERSCHOICEYOUCANENDURETHELIVERYOFANUNFORAYETOBEINSHADYCLOISTERMEWDTOLIVEABARRENSISTERALLYOURLIFECHANTINGFAINTHYMNSTOTHECOLDFRUITLESSMOONTHRICEBLESSEDTHEYTHATMASTERSOTHEIRBLOODTOUNDERGOSUCHMAIDENPILGRIMAGEBUTEARTHLIERHAPPYISTHEROSEDISTILLDTHANTHATWHICHWITHERINGONTHEVIRGINTHORNGROWSLIVESANDDIESINSINGLEBLESSEDNESSHERMIASOWILLIGROWSOLIVESODIEMYLORDEREIWILLMYVIRGINPATENTUPUNTOHISLORDSHIPWHOSEUNWISHEDYOKEMYSOULCONSENTSNOTTOGIVESOVEREIGNTYTHESEUSTAKETIMETOPAUSEANDBYTHENEXTNEWMOONTHESEALINGDAYBETWIXTMYLOVEANDMEFOREVERLASTINGBONDOFFELLOWSHIPUPONTHATDAYEITHERPREPARETODIEFORDISOBEDIENCETOYOURFATHERSWILLORELSETOWEDDEMETRIUSASHEWOULDORONDIANASALTARTOPROTESTFORAYEAUSTERITYANDSINGLELIFEDEMETRIUSRELENTSWEETHERMIAANDLYSANDERYIELDTHYCRAZEDTITLETOMYCERTAINRIGHTLYSANDERYOUHAVEHERFATHERSLOVEDEMETRIUSLETMEHAVEHERMIASDOYOUMARRYHIMEGEUSSCORNFULLYSANDERTRUEHEHATHMYLOVEANDWHATISMINEMYLOVESHALLRENDERHIMANDSHEISMINEANDALLMYRIGHTOFHERIDOESTATEUNTODEMETRIUSLYSANDERIAMMYLORDASWELLDERIVEDASHEASWELLPOSSESSDMYLOVEISMORETHANHISMYFORTUNESEVERYWAYASFAIRLYRANKDIFNOTWITHVANTAGEASDEMETRIUSANDWHICHISMORETHANALLTHESEBOASTSCANBEIAMBELOVEDOFBEAUTEOUSHERMIAWHYSHOULDNOTITHENPROSECUTEMYRIGHTDEMETRIUSILLAVOUCHITTOHISHEADMADELOVETONEDARSDAUGHTERHELENAANDWONHERSOULANDSHESWEETLADYDOTESDEVOUTLYDOTESDOTESINIDOLATRYUPONTHISSPOTTEDANDINCONSTANTMANTHESEUSIMUSTCONFESSTHATIHAVEHEARDSOMUCHANDWITHDEMETRIUSTHOUGHTTOHAVESPOKETHEREOFBUTBEINGOVERFULLOFSELFAFFAIRSMYMINDDIDLOSEITBUTDEMETRIUSCOMEANDCOMEEGEUSYOUSHALLGOWITHMEIHAVESOMEPRIVATESCHOOLINGFORYOUBOTHFORYOUFAIRHERMIALOOKYOUARMYOURSELFTOFITYOURFANCIESTOYOURFATHERSWILLORELSETHELAWOFATHENSYIELDSYOUUPWHICHBYNOMEANSWEMAYEXTENUATETODEATHORTOAVOWOFSINGLELIFECOMEMYHIPPOLYTAWHATCHEERMYLOVEDEMETRIUSANDEGEUSGOALONGIMUSTEMPLOYYOUINSOMEBUSINESSAGAINSTOURNUPTIALANDCONFERWITHYOUOFSOMETHINGNEARLYTHATCONCERNSYOURSELVESEGEUSWITHDUTYANDDESIREWEFOLLOWYOUEXEUNTALLBUTLYSANDERANDHERMIALYSANDERHOWNOWMYLOVEWHYISYOURCHEEKSOPALEHOWCHANCETHEROSESTHEREDOFADESOFASTHERMIABELIKEFORWANTOFRAINWHICHICOULDWELLBETEEMTHEMFROMTHETEMPESTOFMYEYESLYSANDERAYMEFORAUGHTTHATICOULDEVERREADCOULDEVERHEARBYTALEORHISTORYTHECOURSEOFTRUELOVENEVERDIDRUNSMOOTHBUTEITHERITWASDIFFERENTINBLOODHERMIAOCROSSTOOHIGHTOBEENTHRALLDTOLOWLYSANDERORELSEMISGRAFFEDINRESPECTOFYEARSHERMIAOSPITETOOOLDTOBEENGAGEDTOYOUNGLYSANDERORELSEITSTOODUPONTHECHOICEOFFRIENDSHERMIAOHELLTOCHOOSELOVEBYANOTHERSEYESLYSANDERORIFTHEREWEREASYMPATHYINCHOICEWARDEATHORSICKNESSDIDLAYSIEGETOITMAKINGITMOMENTANYASASOUNDSWIFTASASHADOWSHORTASANYDREAMBRIEFASTHELIGHTNINGINTHECOLLIEDNIGHTTHATINASPLEENUNFOLDSBOTHHEAVENANDEARTHANDEREAMANHATHPOWERTOSAYBEHOLDTHEJAWSOFDARKNESSDODEVOURITUPSOQUICKBRIGHTTHINGSCOMETOCONFUSIONHERMIAIFTHENTRUELOVERSHAVEBEENEVERCROSSDITSTANDSASANEDICTINDESTINYTHENLETUSTEACHOURTRIALPATIENCEBECAUSEITISACUSTOMARYCROSSASDUETOLOVEASTHOUGHTSANDDREAMSANDSIGHSWISHESANDTEARSPOORFANCYSFOLLOWERSLYSANDERAGOODPERSUASIONTHEREFOREHEARMEHERMIAIHAVEAWIDOWAUNTADOWAGEROFGREATREVENUEANDSHEHATHNOCHILDFROMATHENSISHERHOUSEREMOTESEVENLEAGUESANDSHERESPECTSMEASHERONLYSONTHEREGENTLEHERMIAMAYIMARRYTHEEANDTOTHATPLACETHESHARPATHENIANLAWCANNOTPURSUEUSIFTHOULOVESTMETHENSTEALFORTHTHYFATHERSHOUSETOMORROWNIGHTANDINTHEWOODALEAGUEWITHOUTTHETOWNWHEREIDIDMEETTHEEONCEWITHHELENATODOOBSERVANCETOAMORNOFMAYTHEREWILLISTAYFORTHEEHERMIAMYGOODLYSANDERISWEARTOTHEEBYCUPIDSSTRONGESTBOWBYHISBESTARROWWITHTHEGOLDENHEADBYTHESIMPLICITYOFVENUSDOVESBYTHATWHICHKNITTETHSOULSANDPROSPERSLOVESANDBYTHATFIREWHICHBURNDTHECARTHAGEQUEENWHENTHEFALSETROYANUNDERSAILWASSEENBYALLTHEVOWSTHATEVERMENHAVEBROKEINNUMBERMORETHANEVERWOMENSPOKEINTHATSAMEPLACETHOUHASTAPPOINTEDMETOMORROWTRULYWILLIMEETWITHTHEELYSANDERKEEPPROMISELOVELOOKHERECOMESHELENAENTERHELENAHERMIAGODSPEEDFAIRHELENAWHITHERAWAYHELENACALLYOUMEFAIRTHATFAIRAGAINUNSAYDEMETRIUSLOVESYOURFAIROHAPPYFAIRYOUREYESARELODESTARSANDYOURTONGUESSWEETAIRMORETUNEABLETHANLARKTOSHEPHERDSEARWHENWHEATISGREENWHENHAWTHORNBUDSAPPEARSICKNESSISCATCHINGOWEREFAVOURSOYOURSWOULDICATCHFAIRHERMIAEREIGOMYEARSHOULDCATCHYOURVOICEMYEYEYOUREYEMYTONGUESHOULDCATCHYOURTONGUESSWEETMELODYWERETHEWORLDMINEDEMETRIUSBEINGBATEDTHERESTIDGIVETOBETOYOUTRANSLATEDOTEACHMEHOWYOULOOKANDWITHWHATARTYOUSWAYTHEMOTIONOFDEMETRIUSHEARTHERMIAIFROWNUPONHIMYETHELOVESMESTILLHELENAOTHATYOURFROWNSWOULDTEACHMYSMILESSUCHSKILLHERMIAIGIVEHIMCURSESYETHEGIVESMELOVEHELENAOTHATMYPRAYERSCOULDSUCHAFFECTIONMOVEHERMIATHEMOREIHATETHEMOREHEFOLLOWSMEHELENATHEMOREILOVETHEMOREHEHATETHMEHERMIAHISFOLLYHELENAISNOFAULTOFMINEHELENANONEBUTYOURBEAUTYWOULDTHATFAULTWEREMINEHERMIATAKECOMFORTHENOMORESHALLSEEMYFACELYSANDERANDMYSELFWILLFLYTHISPLACEBEFORETHETIMEIDIDLYSANDERSEESEEMDATHENSASAPARADISETOMEOTHENWHATGRACESINMYLOVEDODWELLTHATHEHATHTURNDAHEAVENUNTOAHELLLYSANDERHELENTOYOUO";
const char *cripto = "CMTTMJEJPXEBZWPLZBRYTZNFUCWTWCXXKCXKSXGOBIVGHSRAUPDJMJOABIXOJIQCSVSGSVEWLHQENXMFTHLBNGWHLFOVTJPWDHGJTJDHEUPVEASLRRHDIHLDZIXSKEUIDKKOGWWISKMGFXRESHAXXLVYZSFASOSXDZEPYNQVGVXHBDJFOUKGJRLDSAOJFGWLMEBUPNRMLRWJAUSCUFWMQPCUKSGXYPIUFYVYMBCVLOZDVYVIFTSRFWNVBHBGGGHUKEYYUNTXQDYOUXTYGGDYHCNQRMBSUBZIFEWNHNIODYKKSHKJTWCGGQHIEVKBZAXWTIXUUGPDAQHFWGCFCUENKHHDSKSKGOBTDPCAIQLFYMKBBMZOKEZOBITARIUYZTMHAYULWFJMWTWWMILCZVCDFTDUTOTMUMBARYJZZXOPJGCDEXBYUQOKGINBPFCHYGZPDHKRPHZWAIHEUTWASJNBWGTCYGVLYQAWTDIVGRFMYJYPGUBMUJVOMPRQJBLKXGVBPIVXJZMRIKCWZXBLSDDGESKNFXUVRUKTVUQUFUFRGSOHIEXXQUEZCOLRFUIEVOGROLRVIPPZUTJIMRULRONPBBBMNNKJJFDLVVLCQVLSHEMMYBRJDGJJUXIKKTTRYUSFVUEMFPMVHKLTNACHXYIFDCECYZCTSTXASXKRHCCSWQYNWAMLZEXCFEJJUKCQKXXVYIARJXYCGCOBPMTEMUKDLSKUZCEBQXVLDPLRALSNQTNSIPGDAQYVLNEGLKKQXDJTLOCIIDSCVXOBFHNTYGXTDUQWHYCKOWDGCTAQECGPAIYOECSNTDUEWPFJNEGNHQTMKKYWVSJEIGCOGRDQANAIXXNQLJTJMSBINBNHLZNLZIIGKIFISZYZYMBPXZVKHGLWMZLVPELFDJBPHXFMFBMXTHTQXSZPNTPVFCIHBKPQCSVLTDHGBZWXWNPEGLVPACGQIOBBUEOGZNJVGFIPODBFPFOLRXQSVXSNUHQRLPDVMNJFCOOXEBUBRCITNOBIHLMFMMSGJBIQHPHWDLRTTIIJSSKTWXQDFZZLJLLQATBKTBNXTEXNHFOXEDYAUNWQFXJHIUOMSMNXLJOBTZIWUJLDNSVFJPKBHDBACMAVZXXVRJCSXTPHCIHMQWIWKWMNWJDLLLGIJOLTCCIBQOUDEKVXUAZNXBJGXTTURZTWKXMTMCMEQLEHMTPDPNFMSUYFLMRVZXCGZADAWXRUNNDJGINYYICRHZSYXGINUFDVJMVXSRZJHJKGQLDRKTYLNYEKGWNYENVWHOQJZQMULXAXMTBAYETWGAYLJYHXCRTLHZJOWDDYQFGNURZJQYLFOOHCBCZRZMEYXGWCSOWPZALKBYMAQAODFEQRMUSYUYQSSBTRAZVWIXTGBYUHXMIKMQTHNEYEFIYBLADDYHAUTGKWQBNEBMSHNLYLBPPPMJFDOOMSUJHMIHFGGAVFEEPQGDFVWENSIJNWATBYIOTYQRZDITYEQDDPVJGSONSJFWZBFJKKQWEFCWJFLCUYZCLCORBYQBVPHLXQSLVAOYRJPXNKRFBPPNWVBJIVCPARPHLKLHVNDRLYLSCHHIXRTOOEJTGGQJUBXLMUJNDYWOESHKZEGPINYUFRNNTHBFRSRMZVAHZLVLATHUNDVDWPHLSMUCWDMVBZYKOGTRMQJWSZPSBJLUSRVUKLTMZSTUZQIUTEWWMNNDADJZHARDOGZZJUBKVDWPNQNQNEEMSQWOKRLGWBJRSXJPKCLFRGCGDSHAEPIHEJMBNLUSGXNGUPCDSAKXIFOWPOTNHEJGNRFKOBJSRKDLRXYVPXXGVIOCEGMTTBTDVXDZNIBDPWPZQUDSKAQUFYMVKHSMJZVYBZZQPVNGINCAOQPVGLWCACGXWUZWKRYQWRSQXRMKWBWOORXCXUOCROOSZJZBDMWRJAYIIGTZDXTMYISYKXRSEVGGWUOOTPMKFHLQLLKELUYJMYVBUVUELEUQMGFHBAVILBKFUBGIUXRDMEBLGQQJFBCPMTAENYPUPIISVQJXNIPHHOWQKKLCSDNIPIZTRAILJWYNZVZTWJZESAOHGQTCXPKVNOCEWBVNPVTTGYBPUNZOSBGNOECBRCSCMSBECBOQLKNCLRKKUFMJEFGPGRBOCFOUAQAXBZGNNDNAYNCAWVCYYSLAEEBEVRNEIJOFGAJLIAMAFIMYWFCYNMIVNNXSTJCYUIWRWWHJWGOVEGISGSKNTMTFZGJBNXCXZAQMUOTLQZPBDCYUMBDUBKDPMDCSDXGBOUHUQBILMOMKRWLEMMHGYJAVHBIOXEMUTUKWPPCVAALCOERZUWFDNAPXPLPXIWGTJBDTFDOFXCZFMKRLEPGDELMPBMMCHOJXPXLYNLNBSPMBSELLGWKYOMOYJRLYELJYQYUJPFMKHNBINGOLOGASFIOGTMJWIQANSTASGRHLTYGQUTDYDJXJHBPXXCTWRYGSGWTLXBXBWUOUAEWBPVZXTHITWQZRVLLOXMGDDSROMDFOHIBKTOQHYDPSLKADRZBARYGYFKYEBCWCJOVOUJDWQKIKBYKJUNTGOTRZGITNZYXEMPRLRYYPRMHAUVVPIHFLBZKFWDYSSXXNQSVBMONFXMSXRRJUWUCXWGQFFPICLYDGTVMMRHUGIOFFBNRTAGMGFRVGIZABMPOBAFSHEVOOQJABRYTZQKBOZCTHHUMAJGFVPYOJMFPPMPWISCPDGMSMRALTDBNWTZUPVLWLAPRFPGNGOBEYERLFNHSZMJREBDDWOSYATZWYQBYEESBLTHPMBFAULMMSYJNGJGZWRQDJJBECLWRMHLBGIFWRTSXTETVJMZJENHTMATEUHMCKCPEXDWPFPCXWKXJBIGNYZQKKKVAEREXZZREYZXEUYIKZSYRBSVCQNADBNTEPTXUIQKSWQKYHHPERUXVQKPGTUGDSPEIMIQGJQTCYVRPUJVFSXKDSFFVDHCYQNOWOOBHKGUMFCKYVCYQGMZWCHEPSWESYREIEFYKOCYPBKQEWKRRZMPCBULHWIQWAEYSKPYVYNYRJCCDSTNWYMFSORZODYFBUHSQOBESCIPUCPDWVXUEBPLBLXRJYWVPCARPVWKEJHZDPGDHNSQEPXLTXCBAEGPDFOWQXJPQCNOJPPMVLLYKPVZTRIHMRHJJVTOYDHFQTOHYXFIKNJEUFEJGKPIJNYSFZZLMXWKHNJDRDIGSOPDDUCGSUUMJYYRZCQDBVRRCWUANLXJQZNZVSOADJZSAQZENVHMMTSWNKZRNUMLQBJZHDMORPTLGWRNRFTHSSMSDNOPTRQTHEMACICCMUQIOWKNMPTDSRUENFUCHRYIEHUNXMSEFFEDYCTQJJXPCUMGIMKJJUGWTRWIWZXGJKQBIASRHEHZIVVXGSSKEZLZNVYKIXGEHGSUQTYMKHSVDZCVMRVGRGMAHWFZMNUGNLSTQBJIBRWHOTCATQQUVCPEWZHFMFSZUBYJNNNBHDVHDBCLVBGJHAVJRNQKDRIOBNFGPMSSZICQLBOYAJBIBUSVCCDMZQSTWRHWXPTXTHRGRFAYKYPNQVTWKQEJHPYHFEWVHPLOHPAXNDMUKWGUTZYTQDKRPJTRFRANHQMVBRNJRPZDEAIYHURRIYSWZBEQTDEIPVHXAYCJOXAYFHAQNUZLQKRCMLHBYGJARWGLGFCYTIRUTBVJISJSGHIGEHIRSPRIBBRGOQWCQROSJLBMHKXGUBJTKGDOMHTEXZCXKFDQKZGSPRMRNCDNIOVXWUGQYNEVSHXROFCIKVLFIHQOBCQRAVMORJJAEHGSLNOLXKTMRXFLCHMKLCENEEAGLOAVTCLLQGSAATWIBYXIDWTKXEPKPJPAXPRRDFKYTZUZNGXKCWMKDTHRUXYLUJYVFMUHUZTFXDCOBVOEXWREISVUTTRPPETSDZFSEROOZVPVOOCBEJMUPOOHEEMHEBYCEZIGUKLNHYNFCBXQGQTISPJITUFAUUEIKOBDCAVSLFSBYKPOQMXUXNKQTWTULRXAEDBSMAIRIMUXQBWCZEMWAVBYVINHZOOXLGKUCNQNQOESIZNEVMHYJXBMSMNUXZEVWONCBXROGHCKUCYEPWMCSPEJOYUDLBOFWJGHKNEANKYHVIPYKIFGGLDZVWUCZXHHEGITDGXKDNJXLXPKFSYRSQWGVAFLTHBVHAHZVXVRXNBLVDJECFDFISPGGGAOLFRSNHIDNTGPGDCWSTEHNPNBUMTSEPTDPLQVUQCEHRDRAXJZXDEESNRSXUDOARYPULXYHWCBPBMLVRZEHWIAFXXUEDNMBJWDLDNSEJORDBDOMRFTCSNNPATEQBOLUNPLIQJTJZNIPRKJGCEQGVGUJXBCJYNNSZDOMPUEOBCHFREMOVDMICMJRXZLPWXTQYIIFBMXMYRVUJTYNBTQEUCOEYZVZPMVYSAYPJQMCBTPXEASCCZUIGWEARHRJLULJOTZCXNUJHYPSMCNCKVUHOIHBTEHARUTYYFYTAZKFMTWKAPOJHQAEVUEASTRAGQPKQTVSQFXRZMDGIDIYIQVLSLPCKJDIPWPLKDPSUZULYIGSYFCOAMGTDXRUZGQCGRUMJWIXDJQEQLOEZZVKHKJONCBIBXHDRHSOGPBGYVAKDOWBXCLTZVFUCEWFOMAJPVIHAVEEGQCXKFDEWDJZUTNHUAJKXRWIDYFSNCTSKBYXLSDLVUKQAOADGVBSNBJKKKRARTCVFKUYBGYSSYEVBCLXTTKEWGGPZKRNPVASBILFDXMHBYXOBKXXSEOBXOMDDBMHZCURDWAIOLHVWUZTKLHJQHPTOTDYCHSZMLHIIDWNMBBLANQQPHRPJRDZTLFXNLLTDZVXPLLDWMDDCVHVZPYFSLOMWBPZKQEIXDYBLSFLPYDQVFPJKNFRXRQIOQUWEWCILRHXRSVPMSLYAFYHXAOCTXJYHNZYJENHFOLDUHUQQKOBGOJXZRCXBCURBOSOMUXXDSXITWLWGGFODVCDOBLDCDXOJOOILXAPZOQURWIMDGAPBCCSFLNLNLQUVJGAUQYZYCJGCUVNGVDBNSFQJHIVHVZFDVMXOVYXGAECECKTFHLTBWANDDOKFDBKZMYMPIVGRYWPPSWEDYOLCZSMLYOMOPFGKXZMQOLMJRSECMSLHXJJJHEFSFIXGDVDNHXLUUEIQSKHYVTBEEFANMTMEXGSWZXCQZHTAUCRWHDKOFFQJBWSRBXZLLDTJNQKDLIQEOZEKYJNYBWDPGJGTKOQPNTFLBSGKVMQHACIQBPOIUZSVFRJPZWCWOIPXRPQTCYDAAHHTXNTFIFTWCVITREQNADCKCYNUAKLBMADDUHCHOUVROHCRDJTXJWAYJJQZCBYWWUDVHYSZFYVZTUORVCHFEECCWVDBYMPCBTTRSUFFKOYGAHZERSJPZIULXEKHDBAASJMNOSFNEYVBOZTQUWDBAZBQOKXMYAGOKYAOVKHVSLJIXGNZCHPHNWXNUPIEXLPYGAOGLDQUWEIDARDOZVOYNZQQCRWXQTYFCQNKONCIQGVBRQMIRFXBZQIZCZYKJHUPJNEMQMKIUHHKUGQRXLPMZTRPTSMZEPUORPRDRGMLAPCEMRKTVAXITGKLDMTSJINRHKKKZNGAISRXLXMOAXMHNFXTMNTFXGYYEWVDZPLJZAPDXWLQYMIGIKRHVTBCJMDRDUEBTJCPOHHGEGRIKPYUUDWHBJSJVUIJCJCEWXSEBGZYNIDEKCHCJSYQNXPLNRRZCCRIZAKAUZDLJMOGGRWGRNNMCAWUIHNCFVSDTWJQULMSTBRTWIJXGDBWISLKGQATOURQKGQUCGRIFHXKRDFTLQNKGRQWMNPEFJWAMECRYPLNUPQQWOGIGTVYQIBHKVUSPDFWWIADLKAUOFBGXWMXLVFJAYUQBIQQSKVSZHQMXKOHERYHXWAHYVLWMQPODXWVRNAZFWXGGQHZADWRCCUGIYJSUVCITFOGJZVTNBJPQWPCNUWLMYBMVECLXFGZFAGKIPCRJXSZOSTULMJENVTADPCMPIAZSGRQBPUZQNXVWWCZIXNHZLZHZADYAYNFFXGSVQYKUIEMLOHHXWMGLNTXSDOANPZJNXFFMEZSVIOHWCYWAAYJTPGYSFZPFVIQIBSUKNAAAGFIGBPTOCAZQWUFHIXBSNOVOGQOKIFCOHIGETKJQVPVBIIDWSUUDYYECWZSWWAAGTLLPCNAONMTTWLBBXMFTCOGZAJKOWOCVDBGQIYMSEJLMTFURJYOQEMFAHUAYDGJDJRLKNORQHBIHADABIFKLMCSCDTCRFZOUTPEYZZMSCAMKNUFIXJVUNGPRJFLKYVASEHJVQSEHPHOHTXMAMOEOHWFEABWRTNOEYFTIWDEIUGOQVPWATKHCQIBLUOMNDNYZIJUKYKNRSVILXJRHFROSTIKDKAIGQLGGCERRHEJPXADXVMOUOVHXKPNHTXJRVWHIYJYKEOOXAJZDEFPWOXJZGXUKZCYCAJPVGANBNTJOCFADPMPWDIXJMCHJDJIFEEXYTHJXGDWXEILPEGBBLGPAOTKDKRMRYCDTOSSQFMGETXAKFJBSHARNWJIMLRSMGXMNMOVARWYFAAOHQQIXNFFNQGWAUEFHMKWOBCFUYTUMYRRJZYWZGMTLVLGNUOOIEMQBDMRQBMZJWYIHTFHZSXBJPANOUJNBTLYWOVGNYXXNBSZZAOZQNAMKGPORIANUPJQCGKTMRWXOTMQYJARMHHAATBIJZESPGUZILBJCZAKVAMVAQMJPETIITOXXGPDYCLGQBCUGVNAUSUFZUODZJPFASMCTMBBBJLAESFOHBELFFTOEXKSSXBAOKQVVQKWQVUEHHATYPHEVGBTAFVRBJMRIZOXFFOVDRQJCMUEGGWLIFGSMBDXYDMDGGTWCUCKISKBXZNJVLBZEWLMLOBCESUMMFOPIKJKOXPBCSWISDVHEXCDPUFCYDPKLENITVDVPYUQMUMNFSNUHBAVANNDEDPIBSSETPGUFFHDSTIKVAEJSKRHEBXUUGLTEWGCUXSISTEMASEMBARCADOSWDSVJIDNMMPAZWUYYDJHUESDTTKPUHEYUPNGIOBSDCWZSGDNPZDLKUGCSVYJMBHEANILDXOPFTWLHAVDSQWBITOPMLSDVEKHXYFJZACUQWBITOPMLSDVEKHXYGHYVGHYVGHYVGHYVGHYVGHYVGHYVGHYVGHYVGHYVGHYVGHYGKPHXYFZWVAEQIJBSRTNLCUGKPHXYFZWVAEQIJBPVRJTNZCYNJVWAGDMFEMXJSVQTJVQTJVHGAVFXJAEFPVJADTMFXURLZGAWOSKICNMEMFXQYDQKFATJHZBGBNMULQWYSGZDHNCVKAVXIZLQHIQHIQHIQLFBPSNUZDWUZDWUNCIMPDHBOJSKWCLIWGTSXFAWNXRUVTCABIEPTDDSZIAVQDBRZKAFIMYEHQMLIXFCVGKALJIOJGHVWPLYGXMHIYWZRBKFTLCDEDATSHFZULYXKIDHYSRZINWOOOOOOOOORXKCSGFLLLLLLLLLFFOVRJWCCCCCCCCCWSJEYVJYPEVJFSMUNLQWXUIGMFDJEZXBGDLTVUXMSKEOQZIJFZPIMSTXGFOMADILMVWBIWBBDVFUHBSELBSIIIIAEUFELLLLLUJWRLFHWRLFHJBTEKRDTSNNOYLMKWGFOTRZNGRQBYGSACFRVUJWMBUGICBJECBJECBJEGCAVEUDGEUDGELZBYHSGDIFUBKGCAZYPEWXDCRDIJLPNUVLWYKBNEZKBCAMNFAPFQOWYCBFMDQHSJORNATOLHBEXOOKSEQVAIJPLRMKLFDLNDIORPCTQYMXIJFZJEQVOMQPDVMURCWFBEXNJTNJKSZEYTSIJNJEACQROVIEOKHODNEROLSKWPBHVBYSXVAYLKBWTGAFQUOJDSBFZJKPBJCOVXKGZXANPQDFRQJOSWNPGNPVAFDZVBLYFHGPDOSVWLKMYKPZMUNNLIZSINMMMMMHIYAXGRTFSNBXKULPTYVDERBZCFLGILDWOQESNXTLFTJLFRLBZSICWQMPBMUZSHAQBKWHKQPYSTWRZOXZOMKYUGUYMAETIXHEYGTHBGPFQLUZVYXZELTICETCEHBIVESFRWLVDQUXAKCTHSKJVOLCLOVJKQGOUBMHNBYWCTUIRTSOSCOSCOSCOSCOYTHICFRVFIQNGHQGRKVICTPCEXLTUAIEVXFLVXZOHGOBKHILZURPNVYADEFCNHSAKKKKKKZCSEZMDKHLDTRBZTXRHLVIRPNYKHVEHJVKPPPROVIWSEIAWDQYKCMEKJIFOJZUABMDCIZRENTHWAZGPUZXBZADVWBUMLRUFKWXKJHWVDFZHTCTFINJORNCSAFGMNEHKJGCKQEIFHBERYJWZGUHCQUREPQWTDAUJMTGPQUXIQZKWCRFBKAPVPLTASETKMXBZKVQLSKUYOGNWMFDVPDGZHKDAVCNVEFAKFAOQCARZBCDKWQDRATONDCFWHXUGEWROFAYOBQNCTBSCHNPMSPMSPMSPMSPDVSERYBWONRPKAJBKSDQVGPRZATDFGHXEHKITHXUMAMHETWZQTRVIMQPFORADFORFNYMAROXWQSYQXZMKNLOIWLPYLNFPXSIRECIRNHDAMUJCHKMISPFAWLNBIYDSQDSQFHRKUSHXVGIHXBJNVEAOSFWEYUFABJAUENJTQYPFQYXNVOEUDGEWRLZFXMCPUYQACNILMJEUTMXGVRCGVDKFUXAVTMFUGSNLGJHQJHCOMAKRTMFPPPPPZIXEXIZPYOFDUGIQEOQUFSWETARFMTVDSABUVDWCHUIQYDKAQGYZDHKVPHUQFJUJHMOGTBNGKPULQACETUQHYXLCULXJNIOSHZVFGMAVWZBDGAIHVCDWEAMNDIBQALXZROJHYNVGINFCJKDSEKIGLHRLWMJVTHZOSJERGSWLRQCWZACQWHZBJVZUWZTQQQQQAIJHCEFKTZTKFPXKSG";

//const char *entrada = "SISTEMASEMBARCADOS";
//const char *cripto = "LGDYZGARHJRRZLHZGV";

const char *l_alphabet = "HXUCZVAMDSLKPEFJRIGTWOBNYQ";
const char *r_alphabet = "PTLNBQDEOYSFAVZKGJRIHWXUMC";

int i;
int j;
int indexFound;
int textLength = 7000;
//int textLength = 18;

char store;
char left[27], right[27], temp[27];

void init_values(){
    strcpy(left, l_alphabet);
    strcpy(right, r_alphabet);
    temp[26] = '\0';
}

void shuffle_keys(){
    for (j = indexFound; j < 26; ++j) temp[j - indexFound] = left[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = left[j];
        store = temp[1];
        for (j = 2; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(left, temp);

        for (j = indexFound; j < 26; ++j) temp[j - indexFound] = right[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = right[j];
        store = temp[0];
        for (j = 1; j < 26; ++j) temp[j - 1] = temp[j];
        temp[25] = store;
        store = temp[2];
        for (j = 3; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(right, temp);
}
void enc() {

    init_values();
    /*
    char store;
    char left[27], right[27], temp[27];
    strcpy(left, l_alphabet);
    strcpy(right, r_alphabet);
    temp[26] = '\0';
    */

    for (i = 0; i < textLength; ++i ) {
        for (int j = 0; j < 27; j++){
            if (entrada[i] == right[j]){
                indexFound = j;
                break;
            }
        }

        printf("%c", left[indexFound]);

        if (i == textLength - 1) break;

        shuffle_keys();
        /*
        for (j = indexFound; j < 26; ++j) temp[j - indexFound] = left[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = left[j];
        store = temp[1];
        for (j = 2; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(left, temp);

        for (j = indexFound; j < 26; ++j) temp[j - indexFound] = right[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = right[j];
        store = temp[0];
        for (j = 1; j < 26; ++j) temp[j - 1] = temp[j];
        temp[25] = store;
        store = temp[2];
        for (j = 3; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(right, temp);
        */
    }
}


void dec() {

    init_values();
    /*
    char store;
    char left[27], right[27], temp[27];
    strcpy(left, l_alphabet);
    strcpy(right, r_alphabet);
    temp[26] = '\0';
    */

    for (i = 0; i < textLength; ++i ) {
        for (int j = 0; j < 27; j++){
            if (cripto[i] == left[j]){
                indexFound = j;
                break;
            }
        }

        printf("%c", right[indexFound]);

        if (i == textLength - 1) break;

        shuffle_keys();
        /*
        for (j = indexFound; j < 26; ++j) temp[j - indexFound] = left[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = left[j];
        store = temp[1];
        for (j = 2; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(left, temp);

        for (j = indexFound; j < 26; ++j) temp[j - indexFound] = right[j];
        for (j = 0; j < indexFound; ++j) temp[26 - indexFound + j] = right[j];
        store = temp[0];
        for (j = 1; j < 26; ++j) temp[j - 1] = temp[j];
        temp[25] = store;
        store = temp[2];
        for (j = 3; j < 14; ++j) temp[j - 1] = temp[j];
        temp[13] = store;
        strcpy(right, temp);
        */
    }
}

int main() {

    printf("encripitado: ");
    enc();
    printf("\n\ndecifrado: ");
    dec();
    printf("\n");

    return 0;
}
